### PR TITLE
User/estes/issue123 fix

### LINKED ISSUE #123: Exception when trying to convert Workspace, when multiple identitcly PropertyGroup are present
Hi,
I tryed to convert a old project, but the convertion crashed with this Error:
```
System.ArgumentException: An element with the same key but a different value already exists. Key: Debug|AnyCPU
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.Add(TKey key, TValue value, KeyCollisionBehavior behavior, MutationInput origin)
   at MSBuild.Abstractions.MSBuildWorkspace.DetermineConfigurations(IProjectRootElement projectRootElement) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 68
   at MSBuild.Abstractions.MSBuildWorkspace..ctor(ImmutableArray`1 paths, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspace.cs:line 44
   at MSBuild.Abstractions.MSBuildWorkspaceLoader.LoadWorkspace(String path, Boolean noBackup) in /_/src/MSBuild.Abstractions/MSBuildWorkspaceLoader.cs:line 45
   at MSBuild.Conversion.Program.Run(String project, String workspace, String msbuildPath, Boolean diffOnly, Boolean noBackup) in /_/src/try-convert/Program.cs:line 73
```
The reason is found is that one of the projects had the propertygroups definationed multiple times.
e.g.
```xml
 <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Debug\</OutputPath>
    <DebugType>full</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>    
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Release\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>AnyCPU</PlatformTarget>    
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\bin\Debug\</OutputPath>
    <DebugType>full</DebugType>
...
```
It would be nice if these could automaticly merged.
Also if the convertion crashes when converting one project then it would be nice if there is any info about the project currently checked/converted,

### PR DESCRIPTION
**Pull request by MadEste**
Adds duplicate name check to fix #123

### CODE REVIEW

File: src/MSBuild.Abstractions/MSBuildConversionWorkspace.cs [hunk 1]
```diff
@@ -68,9 +68,8 @@ public MSBuildConversionWorkspace(ImmutableArray<string> paths, bool noBackup)
                 if (MSBuildHelpers.ConditionToDimensionValues(propertyGroup.Condition, out var dimensionValues))
                 {
                     var name = MSBuildHelpers.GetConfigurationName(dimensionValues);
+                    if (builder.ContainsKey(name)) continue;
```
Comment (cartermp) [inline src/MSBuild.Abstractions/MSBuildConversionWorkspace.cs:71]: Style-wise we should use `!builder.Containskey(name)` and introduce another level of nesting. But otherwise this looks good!

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/try-convert?pullRequest=304) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/try-convert?pullRequest=304) before we can accept your contribution.<br/><br/>:x: MadEste [sign now](https://cla.dotnetfoundation.org/dotnet/try-convert?pullRequest=304)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/try-convert?pullRequest=304) it.</sub>
