### PR TITLE
forward to correct package name

### LINKED ISSUE #128: Referenze System.ComponentModel.DataAnnotations gets resolved with wrong NuGet Package
Hi,
The Referenz 'System.ComponentModel.DataAnnotations' gets resolved with a not existing NuGet Package with the Same name.
For this Referenz the NuGet Package is called 'System.ComponentModel.Annotations'
Not sure if there are other ones.

### PR DESCRIPTION
**Pull request by jmarolf**
fixes #128

### CODE REVIEW

File: src/MSBuild.Abstractions/NugetHelpers.cs [hunk 1]
```diff
@@ -1,8 +1,10 @@
-﻿using System.Collections.Generic;
+﻿using System;
+using System.Collections.Generic;
 using System.IO;
 using System.Net.Http;
 using System.Text.Json;
 using System.Threading.Tasks;
+using Microsoft.VisualBasic;
```
Comment (RussKie) [inline src/MSBuild.Abstractions/NugetHelpers.cs]: Why is VB needed?

Comment (jmarolf) [reply src/MSBuild.Abstractions/NugetHelpers.cs]: good question, I think this is unnecessay but I'll check
